apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: python-ocpjtuqz
  janus-idp.io/tekton: python-ocpjtuqz
  backstage.io/kubernetes-id: python-ocpjtuqz
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: python-ocpjtuqz
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
